const express = require('express')
const dotenv = require('dotenv').config()
const colors = require('colors')
const connectDB = require('./config/db.js')
const port = process.env.PORT||5000
connectDB()
const {errorHandler} = require('./middleware/errorMiddleware')
const app = express()
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use('/api/goals/',require('./routes/goalRoutes'))
app.use(errorHandler)
app.listen(port,()=>{
    console.log('服务器在'+port+'端口监听')
})
